<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html>
<head>
<meta charset="UTF-8" />
<title>PHPWord</title>
<meta name="author" content="chandrasekar 1997" />
<style>
* {font-family: Arial; font-size: 10pt;}
a.NoteRef {text-decoration: none;}
hr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 1px solid #CCC;}
table {border: 1px solid black; border-spacing: 0px; width: 100%;}
td {border: 1px solid black;}
h1 {font-size: 16pt; color: #2E74B5;}
h2 {font-size: 13pt; color: #2E74B5;}
.ListParagraph {}
.Hyperlink {color: #0563C1; text-decoration: underline ;}
.Heading1Char {font-size: 16pt; color: #2E74B5;}
.Heading2Char {font-size: 13pt; color: #2E74B5;}
.Title {font-size: 28pt;}
.TitleChar {font-size: 28pt;}
.Subtitle {color: #5A5A5A;}
.SubtitleChar {color: #5A5A5A;}
</style>
</head>
<body>
<p style="text-align: center;">Privacy Policy</p>
<p>&nbsp;</p>
<h1>Customers</h1>
<p>Search by Vehicle</p>
<p></p>
<p>User can change </p>
<p>search criteria in Results page and re-search again if needed right from Results page without going back to home page</p>
<p>.</p>
<p>Search by Brand</p>
<p></p>
<p>Need option to turn on/off t</p>
<p>he ability t</p>
<p>o take them to the</p>
<p> Tire OEM </p>
<p>website. We will </p>
<p></p>
<p>rnable</p>
<p></p>
<p>/disable</p>
<p> this option based upon </p>
<p>if they are a paying customer/affiliate partner.</p>
<h1>Administration </h1>
<p></p>
<p>Need option to turn on/off </p>
<p>links to OEM/retailer </p>
<p>website</p>
<p>s</p>
<p>. We will </p>
<p>enable/disable</p>
<p> if they are a paying customer/affiliate partner.</p>
<h1>Marketing</h1>
<p><span style="font-family: 'Times New Roman'; font-size: 12pt; color: #000000;">aaaa</span></p>
</body>
</html>
